package shared.gestionempleados;

public enum PuestoEmpleado {

	DIRECTOR_COMUNICACIONES, ENCARGADO_TIENDA, ENTRENADOR, EMPLEADO_COCINA, EMPLEADO_JARDINERIA, EMPLEADO_TIENDA, GERENTE, 
	GESTOR_INSTALACIONES, JUGADOR, VENDEDOR_ABONOS 
}
