package backend.service.usuarios;

public enum TipoUsuario {
	NO_USUARIO, ACCIONISTA, JUGADOR, ENTRENADOR, GERENTE, VENDEDOR_ENTRADAS_ABONOS, ENCARGADO_TIENDA, GESTOR_INSTALACIONES,
	EMPLEADO_TIENDA, EMPLEADO_JARDINERIA, EMPLEADO_COCINA, DIRECTOR_COMUNICACIONES
}